version: '3.8'

services:
  chunker-shade-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vibesflow-chunker-shade-agent
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - TEE_ENABLED=false
      - TEE_ATTESTATION_MODE=development
      - DEBUG_ENABLED=true
      - VERBOSE_LOGGING=true
    env_file:
      - .env
    volumes:
      # Mount local directories for development
      - ./temp:/app/temp
      - ./receipts:/app/receipts
      - ./logs:/app/logs
      # Mount source code for development (optional)
      - ./server.js:/app/server.js:ro
    networks:
      - vibesflow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - localstack
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chunker.rule=Host(`chunker.localhost`)"
      - "traefik.http.services.chunker.loadbalancer.server.port=3001"

  # LocalStack for local AWS services simulation
  localstack:
    image: localstack/localstack:3.0
    container_name: vibesflow-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - vibesflow-network

  # Redis for caching participant data
  redis:
    image: redis:7-alpine
    container_name: vibesflow-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - vibesflow-network

  # Traefik reverse proxy for local development
  traefik:
    image: traefik:v3.0
    container_name: vibesflow-traefik
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - vibesflow-network

volumes:
  redis-data:
    driver: local

networks:
  vibesflow-network:
    driver: bridge
    name: vibesflow-network
