services:
    dispatcher:
        platform: linux/amd64  # Explicitly set for TDX
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        container_name: v1dispatcher
        ports:
            - "3000:3000"
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock  # TEE socket mount for Phala Cloud
        restart: always
        environment:
            # NEAR Configuration
            - NEAR_ACCOUNT_ID=${NEAR_ACCOUNT_ID}
            - NEAR_PRIVATE_KEY=${NEAR_PRIVATE_KEY}
            - AGENT_CONTRACT_ID=${AGENT_CONTRACT_ID:-v1dispatcher.vibesflow.testnet}
            - CONTRACT_CODEHASH=${CONTRACT_CODEHASH:-1684d223bf0d4fe4b0a5932ee972969d09a4c97db2f7565f4be7c34388b850f6}
            
            # Filecoin Configuration
            - FILECOIN_PRIVATE_KEY=${FILECOIN_PRIVATE_KEY}
            - FILECOIN_ADDRESS=${FILECOIN_ADDRESS}
            - FILECOIN_RPC_URL=${FILECOIN_RPC_URL:-https://api.calibration.node.glif.io/rpc/v1}
            - FILECOIN_CHAIN_ID=${FILECOIN_CHAIN_ID:-314159}
            
            # Synapse Configuration
            - PANDORA_CONTRACT_ADDRESS=${PANDORA_CONTRACT_ADDRESS}
            - PAYMENTS_CONTRACT_ADDRESS=${PAYMENTS_CONTRACT_ADDRESS}
            - USDFC_TOKEN_ADDRESS=${USDFC_TOKEN_ADDRESS}
            - PDP_VERIFIER_ADDRESS=${PDP_VERIFIER_ADDRESS}
            
            # TEE Configuration
            - DSTACK_SIMULATOR_ENDPOINT=${DSTACK_SIMULATOR_ENDPOINT:-}
            - TEE_SOCKET_PATH=/var/run/tappd.sock
            - PHALA_CLOUD=true
            
            # Server Configuration
            - NODE_ENV=production
            - PORT=3000
